# Generated by Django 6.0 on 2025-12-13 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anilibria_id",
                    models.IntegerField(unique=True, verbose_name="Anilibria ID"),
                ),
                ("code", models.CharField(max_length=255, verbose_name="Код (slug)")),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Название (русское)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название (английское)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "poster_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Путь к постеру"
                    ),
                ),
                (
                    "player_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на плеер",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Аниме тайтл",
                "verbose_name_plural": "Аниме тайтлы",
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.IntegerField()),
                ("hls_480", models.URLField(blank=True, max_length=500, null=True)),
                ("hls_720", models.URLField(blank=True, max_length=500, null=True)),
                ("hls_1080", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="myanime.animetitle",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
                "unique_together": {("anime", "ordinal")},
            },
        ),
    ]
