# Generated by Django 6.0 on 2025-12-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0003_useranimelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="skip_ed_end",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Конец эндинга"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="skip_ed_start",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Начало эндинга"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="skip_op_end",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Конец опенинга"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="skip_op_start",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Начало опенинга"
            ),
        ),
    ]
