# Generated by Django 6.0 on 2025-12-22 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0005_episodehistory_delete_watchhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=500, verbose_name="О себе"),
                ),
                (
                    "auto_next",
                    models.BooleanField(
                        default=True, verbose_name="Авто-переключение серий"
                    ),
                ),
                (
                    "auto_skip_intro",
                    models.BooleanField(default=False, verbose_name="Пропуск опенинга"),
                ),
                (
                    "default_quality",
                    models.CharField(
                        choices=[("1080", "1080p"), ("720", "720p"), ("480", "480p")],
                        default="1080",
                        max_length=10,
                        verbose_name="Качество по умолчанию",
                    ),
                ),
                (
                    "dark_theme",
                    models.BooleanField(default=True, verbose_name="Темная тема"),
                ),
                (
                    "backdrop_blur",
                    models.BooleanField(default=True, verbose_name="Размытие фона"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
