# Generated by Django 6.0 on 2025-12-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
