# Generated by Django 6.0 on 2025-12-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0007_profile_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tg_auth_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
