# Generated by Django 6.0 on 2025-12-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0009_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Жанр"),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AddField(
            model_name="animetitle",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="animes",
                to="myanime.genre",
                verbose_name="Жанры",
            ),
        ),
    ]
