# Generated by Django 6.0 on 2025-12-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0010_genre_animetitle_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Жанр"),
        ),
    ]
