# Generated by Django 6.0 on 2025-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0011_alter_genre_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accent_color",
            field=models.CharField(
                choices=[("purple", "Cyber Purple"), ("orange", "Neon Lava")],
                default="purple",
                max_length=10,
            ),
        ),
    ]
