# Generated by Django 6.0 on 2025-12-30 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0012_profile_accent_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название франшизы"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animetitle",
            name="franchise_order",
            field=models.IntegerField(default=0, verbose_name="Порядок просмотра"),
        ),
        migrations.AlterField(
            model_name="animetitle",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата обновления"
            ),
        ),
        migrations.AddField(
            model_name="animetitle",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="releases",
                to="myanime.franchise",
                verbose_name="Франшиза",
            ),
        ),
    ]
