# Generated by Django 6.0 on 2026-01-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0013_franchise_animetitle_franchise_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animetitle",
            name="kind",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Тип релиза"
            ),
        ),
        migrations.AddField(
            model_name="animetitle",
            name="kind_ru",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Тип (рус)"
            ),
        ),
    ]
