# Generated by Django 6.0 on 2026-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0014_animetitle_kind_animetitle_kind_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="animetitle",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Год выхода"),
        ),
    ]
