# Generated by Django 6.0 on 2026-02-03 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0016_watchlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="animetitle",
            name="shikimori_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Shikimori ID"
            ),
        ),
        migrations.AlterField(
            model_name="watchlog",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время просмотра"
            ),
        ),
    ]
