# Generated by Django 6.0 on 2026-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0017_animetitle_shikimori_id_alter_watchlog_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="animetitle",
            name="source",
            field=models.CharField(
                choices=[("anilibria", "AniLibria"), ("kodik", "Kodik")],
                default="anilibria",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="animetitle",
            name="anilibria_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Anilibria ID"
            ),
        ),
    ]
