# Generated by Django 6.0 on 2026-02-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myanime", "0018_animetitle_source_alter_animetitle_anilibria_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animetitle",
            name="source",
            field=models.CharField(
                choices=[
                    ("anilibria", "AniLibria"),
                    ("kodik", "Kodik"),
                    ("shikimori", "Shikimori"),
                ],
                default="anilibria",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
