"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TG_BOT_TOKEN = config('TG_BOT_TOKEN')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS = [
#     ".ngrok-free.app",
# ]

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "import_export",
    "unfold",
    "unfold.contrib.import_export",
    "unfold.contrib.filters",  # Красивые фильтры (справа)
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "log_viewer",
    "myanime.apps.MyanimeConfig",
    "core",
    'channels',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = 'core.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config('DB_NAME'),
        "USER": config('DB_USER'),
        "PASSWORD": config('DB_PASSWORD'),
        "HOST": config('DB_HOST'),
        "PORT": config('DB_PORT'),
        "CONN_MAX_AGE": 600,
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'home'
# Куда перенаправлять после выхода (на главную)
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

UNFOLD = {
    "SITE_TITLE": "AniPlayer Admin",
    "SITE_HEADER": "AniPlayer",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    # "SITE_ICON": lambda request: static("img/favicon.ico"),  # Если есть иконка

    # 1. Твои шрифты (как в base.html)
    "STYLES": [
        lambda request: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0",
        lambda request: "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
        lambda request: "https://fonts.googleapis.com/css2?family=Outfit:wght@700;900&display=swap",
        lambda request: static("css/admin_overrides.css"), # <--- Добавили твой файл
    ],

    # 2. Настройка цветов (Твой фиолетовый #8b5cf6)
    # Unfold требует цвет в формате RGB (через пробел) для Tailwind
    "COLORS": {
        "primary": {
            "500": "139 92 246",  # Твой #8b5cf6 (Кнопки, активные ссылки)
            "600": "124 58 237",  # Твой #7c3aed (Цвет при наведении)
            "900": "139 92 246",  # Используем тот же, чтобы не было грязи
        },
    },

    # 3. Настройка боковой панели
    "SIDEBAR": {
        "navigation": [
            {
                "title": "Инструменты",
                "items": [
                    {
                        "title": "Просмотр логов",
                        "icon": "description", # Иконка документа
                        "link": "/admin/log-viewer/", # Путь, который мы прописали выше
                    },
                ],
            },
        ],
        "show_search": True,  # Поиск по меню (cmd+k)
        "show_all_applications": True,

    },
}

LOGS_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
        },
        'errors_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'errors.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'errors_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

LOG_VIEWER_FILES_DIR = os.path.join(BASE_DIR, "logs") # Путь к папке с логами
LOG_VIEWER_FILES_PATTERN = "*.log"
LOG_VIEWER_LINES_LIMIT = 1000
LOG_VIEWER_REVERSE = True # Самые свежие записи сверху
